### ISSUE TITLE
What the meaning of function "robust" in HourGlassNet3D.py?

### ISSUE THREAD

**Issue by Talegqz** [Naman-ntc/3D-HourGlass-Network#2]
I tried to understand it but I failed.
Please tell me why using it, thank you very much

**Comment by Naman-ntc** [comment]
Hi! Thanks for interest.
I am afraid I push my code to github in haste and don't really plan to update it much. So the code may be quite jargon. Feel free to ask stuff. By the way you should check out my other repo [Pose Estimation](https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation). The code really fashioned and usable.

As of this, it was an idea I tried (I tried many such small ideas!) which might be little hard to explain but let's see. 

The variable `temporal` is a list (check `ref.py`) which stores the temporal size of 3D convolution kernel. I wanted to have different temporal receptive fields for different layers (more at the start of network, large at the end). The variable stores that information in form of a list and passes it to all the constructors which find the temporal kernel size required in bunch of convolutions they contain. The function `robust` (which seems a very bad name now, apologies!)  slices out some of the temporal features that are not being predicted (corresponding to frames far away from main/central frame).

I guess it's not very clear. Check [this (old commit code)](https://github.com/Naman-ntc/3D-HourGlass-Network/blob/8726b7b34bec3511f22115937faeb36a1194bd72/src/model/HourGlassNet3D.py) which is neat and doesnt have these fancy additions as well. (These fancy additions didn't work as well)

Feel free to get back
Thanks

**Comment by Naman-ntc** [comment]
closing this for now, feel free to open it again!
