### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by victoriamazo** [Naman-ntc/3D-HourGlass-Network#3]
Could you please provide with pretrained weights.
Thank you

**Comment by Naman-ntc** [comment]
Hi, sorry for the delay. Unfortunately I don't believe I would have the pretrained models. If you want to perform 3D Pose estimation models consider using https://github.com/xingyizhou/pytorch-pose-hg-3d on which my repo is based

**Comment by victoriamazo** [comment]
ok, thank you.

**Comment by Naman-ntc** [comment]
Also for 2d pose estimation you can use my code from https://github.com/Naman-ntc/Pytorch-Human-Pose-Estimation

**Comment by victoriamazo** [comment]
Thanks, but I need 3D pose.
