### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by schliffen** [Naman-ntc/3D-HourGlass-Network#4]
I am trying to run your scripts, but faced with some problems. The main problem is the data issue; you used h36m data set and reprocessed it. My question is about data preparation. Can you please explain how did you do that or can you provide data preparation scripts as well?

Thank you

**Comment by Naman-ntc** [comment]
Hi,
Thanks for the interest. Unfortunately I was using preprocessed h36m dataset and don't have very good idea about preprocessing. Most of the code is based upon awesome work done in [this repo](https://github.com/xingyizhou/pytorch-pose-hg-3d). 

Maybe that will be helpful!
Thanks
